### ISSUE TITLE
No module named 'scipy.misc.pilutil'

### ISSUE THREAD

**Issue by daiyl** [nikaashpuri/sarfa-saliency#4]
In "visualize_atari/jacobian-vs-perturbation.ipynb", 
`from visualize_atari import *` will report 
> ModuleNotFoundError: No module named 'scipy.misc.pilutil'

The module `scipy` after version 1.3 does not include `imresize`  no longer.

**Comment by shripaddeshmukh** [comment]
Referring to : https://stackoverflow.com/a/57252715

You can simply downgrade the scipy version to 1.2.x. (This worked for me.)

Steps to downgrade (It is recommended to use a virtual environment.): 

1. Uninstall current scipy version : 

> pip3 uninstall scipy 

2. Install 1.2.x : 

> pip3 install scipy==1.2.0



Let us know if that works.

**Comment by daiyl** [comment]
> Referring to : https://stackoverflow.com/a/57252715
> 
> You can simply downgrade the scipy version to 1.2.x. (This worked for me.)
> 
> Steps to downgrade (It is recommended to use a virtual environment.):
> 
> 1. Uninstall current scipy version :
> 
> > pip3 uninstall scipy
> 
> 1. Install 1.2.x :
> 
> > pip3 install scipy==1.2.0
> 
> Let us know if that works.

Thank you. It works.
