### ISSUE TITLE
Issues arising due to path setting of go_saliency.py

### ISSUE THREAD

**Issue by Okiii-lh** [nikaashpuri/sarfa-saliency#8]
I am learning your method to explain the go agent, and have built the environment as the requirement.txt said, but while I used the go_saliency.py, I find it still have some library that could not be load:coords、dual_net、strategies、sgf_wrapper.
I have spend a long time to resave this question, but failed, could you tell me what items should I notice when I build the environment ? thanks!

**Comment by shripaddeshmukh** [comment]
This issue arises if the paths are not set properly. 

Directions to correctly set the paths:
1. Clone minigo from [here](https://github.com/tensorflow/minigo)
2. Paste all the files from sarfa-saliency/go into the minigo folder. So, for ex., path of go_saliency.py file will become  minigo/go_saliency.py, and so on.
 3. You need to download relevant model weights from [here](https://drive.google.com/openid=1HLwxTqbGWxZRu4tOqTJjoqXOLue3JOVw) and paste it in folder 'minigo-models/models/' (You might need to create these directories, if they don't exist already.)

 Let us know if this resolves the issue. I would recommend you to also go through [readme](https://github.com/nikaashpuri/sarfa-saliency/tree/master/go) page, it will be helpful in setup.

**Comment by Okiii-lh** [comment]
Wow, it resloves my problem,Thanks

**Comment by shripaddeshmukh** [comment]
@Okiii-lh, good to know! 

Closing the issue.
